// Code generated by logcopter-gen; DO NOT EDIT.

package main

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.markdown-quizz.cmd.markdown-quizz")
